config/routes.rb
Rails.application.routes.draw do

  get 'terms/terms'

  
  devise_for :users, :controllers => {:registrations => "my_devise/registrations"}
  resources :videos

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :videos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :nombre, :escuela, :carrera, :semestre, :telefono, :ad_info) }
  devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :nombre, :escuela, :carrera, :semestre, :telefono, :ad_info) }
end

def stored_location_for(resource)
  nil
end

def after_sign_in_path_for(resource)
  	videos_path
end

def after_sign_up_path_for(resource)
    videos_path
end



end

app/controllers/my_devise/registrations_controller.rb
class MyDevise::RegistrationsController < Devise::RegistrationsController
  protected 
  def after_update_path_for(resource)
    videos_path
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def terms
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
    @videas = current_user.videos
    @video = Video.new
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.user_id = current_user.id

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:video, :descripcion, :user_id, :terminos)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlumnosBrose</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://use.fontawesome.com/8e56b09395.js"></script>
</head>
<body>

<div id="fondo">
<div class="hidden-xs">
<span class="img2"><%= image_tag ("r1.png")%></span>
<span class="img3"><%= image_tag ("r2.png")%></span>
<span class="img4"><%= image_tag ("r1.png")%></span>
<span class="img5"><%= image_tag ("r3.png")%></span>
<span class="img6"><%= image_tag ("r4.png")%></span>
</div>
</div>

<% if alert %>
	<p class="alert"><%= alert %></p>
<% elsif notice %>
	<p class="notice"><%= notice %></p>
<% end %>



<div class="container">
<div class="col-md-8 col-md-offset-2">
  <div id="formario">
<%= image_tag ("brose.gif")%> <br> 
<%= image_tag ("logo.gif")%>
<%= yield %>
<br>
    </div>
  </div>
</div>


<% if current_page?(root_path) %>
<div id="ppt">
<div class="container">
  <div class="row">
    <div class="col-sm-6">
    <h4 class="red">Convocatoria</h4>
    <%= link_to '/Convocatoria.pdf' do %>
      <%= image_tag ("fondo1.png")%>
    <% end %>
    </div>
    <div class="col-sm-6">
    <h4 class="red">¿Qué es Idea Lab?</h4>
    <%= link_to '/Idealab.pdf' do %>
      <%= image_tag ("fondo2.png")%>
    <% end %>
    </div>
  </div>
</div>
</div>
<% end %>

</body>
</html>

app/views/terms/terms.html.erb
<h1>TITULARIDAD DE PROPIEDAD INTELECTUAL</h1>



Por este medio cedo y convengo en ceder a Brose, o a aquella entidad que Brose lo determine, todos los derechos,

titularidad y participación que pueda tener o adquirir en o sobre cualquier Propiedad Intelectual que se relacione en forma

total o parcial con los negocios de Brose o con las investigaciones o desarrollos que Brose esté efectivamente realizando o

que pueda demostrar que espera realizar, en la medida en que dicha Propiedad Intelectual no sea para este momento propiedad

de Brose por efecto de ley. Asimismo, me obligo a otorgar todos los documentos y a hacer todo lo que sea necesario para

perfeccionar o de otra forma garantizar a Brosela titularidad de la Propiedad Intelectual cedida por este medio. Pondré por

escrito cualquier Propiedad Intelectual que me sea revelada o que desarrolle o aprenda en el transcurso de mi relación laboral y

que se relacione con los servicios que presto a Brose, aunque ya esté en ese formato, y comunicaré a Brose con prontitud toda

esa Información Confidencial. Tanto durante mi relación laboral como después de su terminación cooperaré con Brose, la cual

sufragará los gastos razonables, en la protección de sus derechos en y sobre la Propiedad Intelectual. En el caso de que Brose no

pueda obtener mi firma en algún documento que se necesite para algún proceso de solicitud de derechos de autor para dicha

Propiedad Intelectual, por este medio irrevocablemente nombro a Brose y a sus funcionarios y mandatarios debidamente

autorizados como mis representantes y apoderados, para que actúen en mi nombre y representación y realicen todos los actos

permitidos por la ley para lograr la obtención o emisión de patentes para dicha Propiedad Intelectual, con los mismos efectos

legales que si hubiesen sido ejecutados por mí.

<br><br>

Por este medio irrevocablemente renuncio a todos y cada uno de los derechos morales que pueda tener sobre la Propiedad

Intelectual creada conforme a este Convenio (el “Producto de mi Trabajo”), o cualquier parte de ella, en lo que concierne a

su uso por parte de Brose. En el caso de que dicha renuncia no sea exigible, convengo en otorgar y entregar a Brose, sin

ninguna remuneración adicional (salvo gastos menores), una renuncia a mis derechos morales en lo que concierne al

Producto de mi Trabajo y a su uso por parte de Brose. Reconozco y entiendo que el término “derechos morales”, según se

usa en este Convenio, incluye el derecho de un autor a ser conocido como el autor de su obra, impedir que otros sean

nombrados como autores de su obra, evitar que terceros realicen a su obra cambios que la deformen, e impedir que terceros

utilicen su obra o su nombre de forma que afecte negativamente su reputación profesional. <br><br>

Durante el transcurso de mi relación laboral con Brose y por los seis (6) meses siguientes a su terminación, revelaré a Brose, con

prontitud, toda la Propiedad Intelectual que se relacione total o parcialmente con los negocios de Brose o con las

investigaciones o desarrollos que Brose esté efectivamente realizando o que pueda demostrar que espera realizar, de la que

haya tenido conocimiento o que se haya relacionado directa o indirectamente con mis servicios para Brose, y que haya sido

creada, concebida o puesta en práctica por mí individualmente o junto con otros, ya sea patentable o no patentable y esté o no

protegida por derechos de autor. Reconozco y convengo en que se presumirá que cualquier Propiedad Intelectual relacionada con

los negocios, investigaciones o desarrollos de Brose que haya sido creada, concebida o puesta en práctica por mí

(individualmente o junto con otros) dentro de los seis (6) meses siguientes a la terminación de mi relación laboral con Brose, ha

sido concebida o realizada por mí durante el transcurso de mi relación laboral con Brose, a menos que yo demuestre lo contrario.

<br><br>

Por este medio cedo dicha Propiedad Intelectual a Brose. <br><br>

Este Convenio no requiere que ceda ninguno de mis derechos en alguna invención, siempre que pueda demostrar que no usé

ningún equipo, suministro, instalación o Información Confidencial de Brose; que la invención fue totalmente desarrollada en mi

tiempo libre y no proviene de ningún trabajo realizado por mí para Brose; y que la invención no se relacionaba, en el momento

de su concepción o de su puesta en práctica, con los negocios, investigaciones o desarrollos de Brose de los cuales haya tenido

conocimiento o que se hayan relacionado directa o indirectamente con los servicios prestados por mí a Brose. Reconozco y

convengo en que todos los materiales creados, preparados, aportados o escritos por mí, en forma total o parcial, serán trabajos

realizados bajo relación de dependencia o por encargo. Antes de ser contratado por Brose no realicé ni adquirí ninguna

participación en invenciones que sean objeto de patentes emitidas o de solicitudes de patente pendientes, o que puedan

convertirse en la base de una o más solicitudes de patente.

<br><br>

app/views/videos/_breadcrum.html.erb
    
<% if current_user.admin? %>
<div id="tabs">
	<div class="tab">
		<a href="<%= videos_path %>" class= "<%= 'active' if current_page?(videos_path) %>"><span class="fa fa-video-camera"></span>Videos</a>
		<%= link_to "Cerrar sesión", destroy_user_session_path, method: :get, class: "fa fa-times" %>
	</div>
</div>

<% else %>
    <div id="tabs">
    <div class="tab">
      <a href="<%= edit_user_registration_path %>" class="tablinks <%= 'active' if current_page?(edit_user_registration_path) %>"><span class="fa fa-user"></span>Mi Perfil</a>
      <a href="<%= videos_path %>" class= "<%= 'active' if current_page?(videos_path) %>"><span class="fa fa-video-camera"></span>Subir Link</a>
      <%= link_to " Cerrar sesión", destroy_user_session_path, method: :get, class: "fa fa-times" %>
    </div>
    </div>
<% end %>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div id="instrucciones">
    <p>
      Graba un video en YouTube de máximo 2:00 minutos, dándonos a conocer los siguientes puntos:
    </p>
    <h4 class="red">A:</h4>
    <p>¿Por qué te interesa participar en Innovation MX?</p>

    <h4 class="red">B:</h4>
    <p>¿Por qué crees que tú puedes aportar innovación al proyecto?</p>

    <h4 class="red">C:</h4>
    <p>Menciona un logro significativo (escuela, trabajo, etc)</p>

    <h4 class="red">D:</h4>
    <p>Para ti, ¿qué es innovación?</p>

    <h4 class="red">E:</h4>
    <p> ¿Qué piensas del trabajo en equipo?</p>

    <h4 class="red">F:</h4>
    <p>¿Qué conoces de Brose?</p>
  </div>
</div>

<hr>

  <div class="field">
    <%= f.label :link_del_video %><br>
    <%= f.text_field :video, :required => true %>
  </div>
  <div class="field">
    <%= f.label :Comentarios_adicionales %><br>
    <%= f.text_area :descripcion %>
  </div>

  <div class="field">
    <%= f.label :terminos %><br>
    <%= f.check_box :terminos, :required => true %>
    <%= link_to "Acepto términos y condiciones", terms_terms_path %>
  </div>
  <div class="actions">
    <%= f.submit class: "button button_red button_block" %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Video</h1>


<%= render 'breadcrum' %>


<% if current_user.admin? %>
    <% @videos.each do |video| %>
    <div class="row">
    <div class="col-md-4 col-sm-6">
    <div id="cajita">
    <%= link_to video do %>
      <h4> <%= video.user.nombre %> </h4>
      <h5> <%= video.video %></h5>
    <% end %>
    </div>
    </div>
    </div>
    <% end %>

<% else %>

<% if current_user.videos.present? %>
<% @videas.each do |video| %>
<div class="row">
<div class="col-md-4 col-sm-6">
    <div id="cajita">
    <%= link_to video do %>
      <h4> <%= video.user.nombre %> </h4>
      <h5> <%= video.video %></h5>
    <% end %>
    </div>
    </div>
    </div>
    <% end %>

<% else %>


<%= render 'form' %>


<% end %>

<% end %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<br><br><br>

<p>
  <strong>Nombre del Alumno:</strong>
  <%= @video.user.try(:nombre) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @video.user.try(:email) %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @video.user.try(:telefono) %>
</p>

<p>
  <strong>Escuela:</strong>
  <%= @video.user.try(:escuela) %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @video.user.try(:carrera) %>
</p>

<p>
  <strong>Semestre:</strong>
  <%= @video.user.try(:semestre) %>
</p>

<p>
  <strong>Información Adicional:</strong>
  <%= @video.user.try(:ad_info) %>
</p>

<p>
  <strong>Link de Video:</strong>
  <%= @video.video %> <br>
  <%= link_to "Ver Video", @video.video, target: :_blank %>
</p>

<p>
  <strong>Descripción del Video:</strong>
  <%= @video.descripcion %>
</p>



<%= link_to 'Editar', edit_video_path(@video) %> |
<%= link_to 'Regresar', videos_path %>


<br><br><br>

app/views/welcome/index.html.erb
<%= link_to "REGISTRO PARA ALUMNOS", new_user_registration_path, class: "button button_red button_block" %> <br>
<p>Si ya estás registrado <%= link_to "inicia sesión", new_user_session_path %></p>